name: Build Release APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Decode Keystore
      run: echo "MIIKpAIBAzCCCk4GCSqGSIb3DQEHAaCCCj8Eggo7MIIKNzCCBa4GCSqGSIb3DQEHAaCCBZ8EggWbMIIFlzCCBZMGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFDA6Twjt1HblLgVKvqFG5nLh5RK3AgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQZBKxyEekikXyK1Ce7a5FjASCBNAv2kmNcsSBC1VKrEbsNs9KXDen2TPoSrg1FzG5UcKkrGQHFuxwwgtyc7jZukN1ckK/RPx+LfdSrnoznN+aWEWeg/oF5wjQn/DLXD3j8Tq4O28tzMZ4R5nqAOtq+z/J+l4CesxYoI7h9+gJLOtDgA6mxoX9SdFlPUEiQGvI4kHgvOu+IMos4v+WHh2jI+t8tmxAvw5mS3aStMYqr1kW1m1MGbJSMyzf/9Qa56Dtw9NnuwEAg6PBcNlqVlPqjXGyMPOzOi6YXRypBlXcSlp/JLNHuty0RoNaWh0kTfjAUspMqGII+MkWmuUXhvwuDDL3Fo/e3E/tJ95GxYhfQiR8b2lsAIWPGnUKLM06pOda1uk+T3nz+7Q7r1REgc+91sA6vqu+utNVFb3UjhtSFlAzfjAvT3WLy5xlY/hIdxCuf3HPbey7Iumku446/eNO/LLCup/2mYsY3fVyTaZNEkHYUmenh8A7sAE+yAd6onvv34CIqO3S02zEblCD9vYJ+VJ87HTwq77BSd10NCPNs2yyodIEppguw/INIHV4dBr/tn2QAZqceuUHCtqii7edrzXqqY48il9NsYSspDlWC0b2F2/BdRLOZ6xWWcgHQy5qMOXRYMJOPV0JYrL6j/VOBGFcgIXgEPbJ1K1DUnneuejsnAO3cS+DlYl7m/864ZqrtTD7JcgYqdZZ/YuNwXyo5Iw3IIhdq+HTXk9iStIBeOcxb2erhn0zEgJhB9GorCYcUQQi0Lo6XsJsYV4FCxAsVsZcpxPwloBbaNQoRXwBnEwiJ4rMLpJS/HtBdmTPSN5CCzGGmM1+eZcqpyif8J8HIYgTIsyzABloGubCH1BezjQwfAH+72KMMJDkMvTRUq1heOZvrsxJbJ/Q0GQF/ZkmUmrJpmZoDfYQrTtM5VIs9Zw90EL5Zy5DCwP1X3OqZqByX0XwCDz8bXq25B2F6fsIT+4T0+sUu3B5Ss6PPqd+cExqV25cMLwjUmev1r9iq+3//A5WvK1YdAB6nJ7FBpbORC5lOxiZ1OabIWHurWxwdVD+PixfmID5sD2ENQesebssclogJxBCGVgrzN8D+jdisoRHdp7+U2ie30hwkH4srszxqxiMGxkmizoWbzoXPPxL6XsOQU3SDgMnzgcL5GWNOV/30feqfXr+hh0iwdjPMCQ0ggDrcrrGHTBS4IYJ+UqkIRfjCrIKgjxjkO+NbRNhBinf8kCd8P35sgPgb0uUykHda3HgxGEaUlILV4+KeTFLg0ofHm03mXaDIWKy6GAlJ8t6JtQiBZY35TJrgl3mw7bh9EbK8JKvGTb9eVwSilxzME4SNvgsaZ61oCEKuAQIXOIu1cax1Qy/ThiGp9yRsa9SDOktZiQWJHdzeSeFgY90yd4szXOramKD9B6UdN+09lL+ZyEQl+ylfR4EFd6MtIO8AJUSwOh7ErcTfksgbROFGYtknremtN6b9AZiLw3Oo/VnsxNGkytVmXc53An6fcpn1P4PkvbeNE+rpGoMaa8LvytYz0UqNE8F3nxx7xsMjRxzWqca+9R9bLg1TONxE1KTKZUcRL+iiLmiRP2SwO6yFsQ51Tm+VA6fozNMecsFLzniXgz/isYvqcvEc2Edthd6Gp73Q+emc7rynGkfmbwfcikqbzFAMBsGCSqGSIb3DQEJFDEOHgwAdQBwAGwAbwBhAGQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTc4MjUzOTIzMjczOTCCBIEGCSqGSIb3DQEHBqCCBHIwggRuAgEAMIIEZwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBQ0IvUwN7fe6DjdrIWLXeC6LmGfngICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEGrNoSrx7ESAiAkUocXw+cSAggPwkNhO6RFjWjgOdsv5O9TUPPK5hLv1IZ0UmIMzUuKJH+x+696BwHEwHug65zOG3TzkGRCE5ed2Aa+OHkh+Yth8g65bhw3+MfZcOfs030pxrAJx00oSx0spFsju9w+fo0I0hbZkBeZeAgg41T+vynw/pquTc4jQTJXly0UaRQtRRbU8K8W3tXmNfMs62G2Fdgot7o173JPK4a55jKySdWB3NcKZVjmqRU7/52WEWqpWEOKHDIM4Cz+DSdS/S9tUBGFUlPFNYlO2OYZMZYkZyWLIU66cm3cjk3C4gNmIQzm26W8/DC5BvPm8dVDjtbdoip2oHDSnc1WDYJq5Nz0MYHAAnpt8r8GhUBJEKZ7Ut78CboAhWDFMmrQshQYy+Otprb18/jbRQe4Wpsm7f+qrwPXvgZ+kp/c6armMWEn/FQ4Y/n08Jv40FADwJTjpS52raaOYSatfW9UNU+TMZmWgEVv/nIJpaF9vZAixg00U5MIGopCaH+RVhPjQ242Nu+hD/+2UsjCQo6vKUm6dSVL5ZDJ0+cTWb96Rz+IiVlyEldrQuDv9AX2CG51uymj0SRWv8pIOmxGou4IV7hAf/U6ope7fWxJkeByHsUTjLes9WvszrGrdCSMVpcB0Vs/GGYBpsu8LqJuKuSXjGwPuLsYHHrd77qIHfaJqosXWb5WZASUbsOh6Lb/94YzmAeJ7jAdFAjRRPoLcbDxjgJGvoFXrUCYCnUnrvzQXmfptX27uJFShpcLYKjZHIRxdKKS4c1O4SsSZw2ZYolvrZf8KJMNzz/wu9k1uFNeiNETyGDcHjom6OB9tPVSNaHPXlA8QCiaMpEBe9CN+4pkF+fmq96pyWFnghZUJ7D+4PM5VjGyItzOLjaFqLLBJSVogsNjlLnjMm4aSKgrM5kkMIk3WXNb1xluE0l8pMSftt2Duti2DWWKPOrsPmn9fX2D5sT1g7vTH0njrZuvNHkggimyaGYMRVieDdgGORKfppU2Tr0NknRNvq1ZMfGR9GoU8BPuFgEMmDVpfPLb0SUmbeGpEx9DB8WGB9qyXdIXNezarJafeevMPzMkUAR7yqXFUREGKQda556sSldL+Gjd6KMDKTxrVmChAqSPlFVjH1Tjt6bpEQEL9xbfXkPsZx/2vuPsTnCZmQlBPoetqt+tngEOfmiSXGF4hcyL1Fxc5NBVKdXIk33cf4Ur6nDDPmnn3PpUV4zVWPNkz06kTdZ0Od/nfU3o6PmqrGJORcJEHMJo8LHhup/UT7A5C74+l1v8ATKp6fBnkk2zIwdLbAJhVKlHaUcX1LaQ+Tdi5VoBGRwjwjSjaQavYntGAlK3fVa1U1/RsIP5TGstkME0wMTANBglghkgBZQMEAgEFAAQg40ywnBVZFJp81c4fHFqH2luaa3AdxfuYYZfcJ21NTVUEFBPbJZSTf9Jes4kb6TZKTZiSp6D/AgInEA==" | base64 -d > ${{ github.workspace }}/my-upload-key.jks

    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/my-upload-key.jks
        STORE_PASSWORD: mypassword123
        KEY_PASSWORD: mypassword123

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: CipherShield-release
        path: app/build/outputs/apk/release/*.apk
