name: Build Release APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Decode Keystore
      run: echo "MIIKrAIBAzCCClYGCSqGSIb3DQEHAaCCCkcEggpDMIIKPzCCBbYGCSqGSIb3DQEHAaCCBacEggWjMIIFnzCCBZsGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFNkxcO6TzmQEyMSt0zQqkdgQVEK7AgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQWxsTHXwUdQzOuGhfuC8PEwSCBNAHGT6gGrCj0WxHNOBP55j1IN5TtspSyVVJ7CpmLyLJuwHD/usrcs3XwPYXsAgonyUeo/MNUZtHZh0ASOt4I/nfoW5kaBM1w2LzutHzmPd+TsNUbUDqr72YpZkhjZU/shrYBSBmgn8pR5VvM/Z8Lea+TnNJYG6N5T0gYpEHWocUvw5ssTET06Wjkvs8KErWH0Vpsg4jjJRqtDirssZjMsNn6FfSD+1vh7UV2hdZZVaD8+uzlQfvtke7BaQjHSvly6hZQ8Kpbc1bxmZRnbDLB4aYwNkyCi6ato/goI4iNOt5B1k+EGFtMiAYOt55ELein1U8/p1uZ5lGc5Tn7qy7uPDuWZfrRc2fLRSVaicHjXM80UD4OpDklYq6PsfwFQfcPGuSnkJGJqslIqPAkn3958bFQBT12VFOPYPHMJSEnAMbo0Q0OYGFBtq/lDXcgiA5K4w6ts7lNI7rwWimvCym4N/i4QnyoxS8632dFVdPbp4+9TuID2GwrC9WgtDJMq1cbqbOrIu0/JlXSPmlL6zJ8i6IKB4u8IHt7YD0iZjtCMFXBzQs+XMaf9WcPfDXz8n+d1Rb4krMSIpAdFx9sJZIIRQKqg0bzkOr5BcatNENOxwk6Dvh/oAsL6a53kQmlF5YIatxmcJKYYgfuxrSHLTWCoc5Tb0jIAxTtBZni8YTfjUU43IS9mfklUl49aIJ/8Q1y2SUFothYN3d/1sE6cR06eufUYYgEuI1BCENuF9oXS3/FszO/bZVG6BOm92qeassrFNnJNB9QeATE8Gnz6+2h9pX0zIPTSMtcbpNq/gOshYIr3lfC7ASv1Z0AOodwDgwLtlgik4GZ7NoG5u/hPSoUOnk2yciDBri1CaU11leRWTbyv68ZC1oZe7XpEKbC6icDgKCciDNHKxXLMT8WHdRkuGA/U0aNNPzN64eachmMhbMy5DFYM5WKuaDthbYyizuYHsQ7aqyOtBLUkfV14yGN/qxq8mGr1U5a/u83Rn1do0FswUPYoWt4fPedyKmD4smO28EL6TdYUSVa43AqLqVKyQfw+oA/GrHFREib7CE3TvmEQTUsImfaUeBMIbWF/3TQtkeb+jU9mTOL5C0cF+EqCRY7zxkcP9Q4iUewAoil0NUk+BnyMtV2MQ4AxiVQMQjZM6LFjl8P1GgZFmZlpkgeufhpbKLe8x4AkbvZ9+M2NW8QuZjrzdUTKwpjXJoj3KMGqcg9l+KuUWqn1hKRvsZCXjMgFyksqBdl8EbqUwMXwYalzqjLYyeu0PBNnOtkTOUnv7WtCM2lj4aBC80sAdTs6BhOX1duO7rGdRg36fCtf1YhWZVJZZZzQPvpjvGVrdMP44SkveUCrfiSBzWc/ijqyasQoF5R7Vo4/nfzql0QJjp9kQk9tQiHoPotOsVqVDZkz/2BvFhgjdrIwHQw9WONzB1HXnKfmU9knWEORJBWQ9Rl9vKmvhjZuibp1PajB5vWE+dfplO4sEjaIg2QiJ2dW0qGvqPaRbrHOEfpXRyYDy3cnDA5WPSGJylo+QKkG+GRKqoDyRkeWFYo9kJIthKa1EVpTvbWL5vjezQK/mylNuvSEWGU6of8FbUrS0p3h8Xc7AZ27WaZQrAaVYMblluWm04dNVQ28FbU7SIggkEBvdwWjFIMCMGCSqGSIb3DQEJFDEWHhQAYwBpAHAAaABlAHIAXwBrAGUAeTAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzgyNTM3ODMwMDk2MIIEgQYJKoZIhvcNAQcGoIIEcjCCBG4CAQAwggRnBgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFOJyEjuF/tjU5mmsn1mxjS2rbajLAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQu/z3I82jV5ukzz+w/0vFJICCA/AJ+vaoGi+sGM0p6moAaIV39xWfM5HDgBMdMSz2xdxMDk26NRd1d8w2jHxVdiMwTJPTkEU1B6zSrQcQTGzdEfo4+NNRWpZJS1a8yRtNh2eyvRnjt9QYbPdsqSRBZ4fsYs6ASsomCD8mrukTKpSYvDVwLx5qKQLy2F1rBodS5KEjKwwzrKd1b8tuXMiFLTTmdwIBCojTTG88rAnAjqU5sYMTI4qmH1NIvrefo4Nsh7K2KP1YY1qYgZ4Y+MJjSVTMehL0GokI5RBDIFlRdXxPFFEn3tYdci1pK+PU5jvRIJC1sZEXSNN5f6tqNaz98AOis+47VAhCi6J26GQmXzkcPXNE9NWM+uUKKHLet11pD6XOK+gJZ5HM6jcA+vgOz407SQ7ddZO+pxwsgm+Xr2yy0bDUGuLhhorRLAf8rpfvhKkBpW3aeVWxl/0CUaZF9wwdPOvwMKUHjQHW/9Y2lHUN2Rsa3jzq7yAWVybb/YvquyouHbc2Ini58f/cYt6punqw5yAR5Qg5BDeobuhLbq5iYNZIaeRRqjFObX9vkrgYmMIrRMPV7RTvQ98RwkdVjlMmgCHOmCqBAwIsxzw7LPv/k46eLFTS+Gsn8KEZmnovwbCEmLNkpEFT0Vde36vu1YBoM8uNabqep/O4Mx825hwZVUHKwDy8Wf0xwGxCHm6ClX5mp5K7z6Kr6M9+8ZfjIHZtsHBByQosTu0fWXg3dN7YIvIP0CAk1dASVLIf6YwVemhwB3o1SvUvZ5eZAYc8znwskLnMsLWmnWLNm02pzAnrKCJd7cM07lH6kdQFo+4TRQ0hsK5YhtsgPV4JCFumL2C4EI0SoMbULWHNe8m/WIBIV2giXaTMlrtWEW9ynoMla78UxMXGuB71QdUpcDVh7xh/+mNE09Bvzmjix3Bn0c0cq8eLcHg4pHzeclzCwmkEF12jfspiUW7dYsqaFqj2pc0jAiJKT6VpB0WphDg42hKcVfAm14FU8hMtvlcwEFGEf/rdLguYkGQlhRutHgsnXpwyWQTWqdxzrmoOdLC1mgZ696EsOEOsYuwuVoEgqR68S40GBCMfgC27nPlVdN5I8VDzVDQJvUBAS5JWb5jGbRWiqKQsZPa1xljV99JXmMSL2uboLU7JB1S4LT+xFwSIZ9mA3UMBYHNwWAUnZnqakPWiFZbecAuE0sp8Aro1z6k7fPxnulr9easSPjLvlykFm/NttU2JT4iyi4+Ca6Sg/NrH+kBYgcmWamewOEcOfHK26VW8IPOfVAxEM7hNA7b2c9vULrlEpk/OTcawbwAFqvNWClFa+soFROA1jhiM9z9rbL86kqEQj2liEqyB8cv3ZQbYC2UwTTAxMA0GCWCGSAFlAwQCAQUABCA4+OvmdbOn5KLoRBM1AnovIswK36Ev+1SDbOw+wVeNTwQUEduP1yvhefzUU0QjTuBKimGsELYCAicQ" | base64 -d > ${{ github.workspace }}/my-upload-key.jks

    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/my-upload-key.jks
        STORE_PASSWORD: mypassword123
        KEY_PASSWORD: mypassword123

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: CipherShield-release
        path: app/build/outputs/apk/release/*.apk
